### ISSUE TITLE
Please add an example on how to add new BC keyword 

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp-project#45]
Hi,
@prudhomm @vincentchabannes @romainhild 
would it be possible to add an example on how to implement new BC conditions?
I'm thinking of BiotSavart , for instance, to compute Dirichlet conditions from a given formula or a call to a dedicated library.

**Comment by romainhild** [comment]
The easier I think is to add it directly in the [lambda](https://github.com/feelpp/feelpp-project/blob/b0563af2590177a38e5d6eda23927e9998435d96/src/update-toolbox.cpp#L27) function.
Something like:
```c++
if ( this->modelProperties().boundaryConditions().hasSection( this->keyword() ) )
{
  auto jarg = this->modelProperties().boundaryConditions().section( this->keyword() );
  if ( jarg.contains( "mynewbc" ) )
  {
    auto const& j_bc = jarg.at( "mynewbc" );
    for ( auto const& [j_bckey,j_bcval] : j_bc.items() )
    {
      // here implement your boundary condition
      // j_bckey is the name of one bc of type "mynewbc"
      // j_bcval is the json section where you can have anything you want (markers, expr, path to a script to run,...)
    }
  }
}
```

**Comment by prudhomm** [comment]
@Trophime this is done in src/
